config/routes.rb
Rails.application.routes.draw do
  root 'logs#index'

  resources :logs, only: [:index, :show]

  scope :api do
    resource :companies, only: [] do
      get '/:company_name', to: 'api/companies#index'
    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  LOGS_PER_PAGE = 25

  def index
    @logs = SugarCrm::UpdateLog.list.paginate(page: params[:page], per_page: LOGS_PER_PAGE)
  end

  def show; end
end

app/views/logs/index.html.erb
<h3>List of logs</h3>

<% if @logs.present? %>
  <%= will_paginate %>
  <ul>
    <% @logs.each do |log| %>
      <% log_name = SugarCrm::UpdateLog.name_for(log) %>
      <li><%= link_to log_name, log_path(log_name) %></li>
    <% end %>
  </ul>
  <%= will_paginate %>
<% else %>
  There are no any logs
<% end %>

app/views/logs/sample.html.erb
<div class="log">
  <div class="header">
    Update <%= @options[:sugar_accounts] %> accounts
  </div>
  <% @accounts.each do |account| %>
    <div class="content">
      <div class="query">
        Search for <b><%= account.sugar_account.name %></b>
      </div>
      <div class="result <%= account.search_result.present? ? 'success' : 'failed' %>">
        <% if account.search_result.present? %>
          <p>Account <b><%= account.sugar_account.name %></b> with id = <b>"<%= account.sugar_account.id %>"</b> was successfully updated with <b><%= account.search_result.company.to_sugar_data.values %></b></p>

          <% if account.search_result.contacts.present? %>
            <% account.search_result.contacts.each do |contact| %>
              <p>Contacts <b><%= contact.to_sugar_data %></b> was successfully added to account's contacts</p>
            <% end %>
          <% end %>
        <% else %>
          <p>No data found</p>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="footer">
    <% if @options[:error] %>
      Update was finished with an error:
      <div class="failed">
        <%= @options[:error].message %>
        <%= @options[:error].backtrace %>
      </div>
    <% else %>
      Update was successfully finished with <span class=updated-accounts><%= @updated_accounts_count %></span> accounts.
    <% end %>
  </div>
</div>

app/views/logs/show.html.erb
<h3>Log <%= params[:id] %></h3>

<%= render file: SugarCrm::UpdateLog.path_for(params[:id]) %>